---
- hosts: all_team10
  become: yes
  become_user: root

  tasks:

        #### SSH
      - name: Permit root login via SSH.
        shell: sudo sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        tags: root_login_allowed.

      - name: Permit password login via SSH.
        shell: sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        tags: password_login_allowed

      - name: Change root password
        user: name=root password=Netsys123$
        become: yes
        become_user: root
        tags: change_root_passwd

      - name: SSH Restarting...
        service: name=ssh state=reloaded
        tags: ssh_restart

      - name: Change root password (Netsys123$)
        user: name=root password=$1$rIkBBrmQ$mxLVk5RKnPFDAZU8Ra2EQ1
        become: yes
        become_user: root
        tags: change_root_passwd
        
      - name: Clear bash history.
        shell: echo "" > ~/.bash_history;
        become: yes
        become_user: root
        tags: clear_bash
