---
- hosts: ubuntudev

  tasks:
      - name: Installing Latest Docker Stack.
        shell: curl -fsSL https://get.docker.com/ | sh
        become: yes
        become_user: root
        tags: install_docker

      - name: Copy Docker container to remote host.
        copy: src=fsports-stable dest=/tmp/fsports-stable
        become: yes
        become_user: root
        tags: copy_dockerbuild

      - name: Docker importing!
        raw: docker import /tmp/fsports-stable fsports:stable
        become: yes
        become_user: root
        tags: import_docker

      - name: Remove dockerbuild file
        raw: rm /tmp/fsports-stable
        become: yes
        become_user: root
        tags: remove_dockerbuild 
