- hosts: foreman
  remote_user: root

  tasks:
      - name: Add Puppetlabs Repo
        #raw: echo deb http://ppa.launchpad.net/saltstack/salt/ubuntu `lsb_release -sc` main > /etc/apt/sources.list.d/saltstack.list
        raw: yum -y install https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm

      - name: Install EPEL
        raw: yum -y install http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

      - name: Add Foreman Repo
        raw: yum -y install https://yum.theforeman.org/releases/1.13/el7/x86_64/foreman-release.rpm

      - name: Change Hostname
        raw: hostname foreman.{{ domainname }}

      - name: Download Foreman Installer
        raw: yum -y install foreman-installer

     # - name: Copy foreman-answers.yaml file

     # - name: Running sed to replace answer file with team number

      - name: Install Foreman
        raw: foreman-installer

     # - name: foreman-rake apipie:cache
     #   raw: foreman-rake apipie:cache

      - name: Integrate Foreman with team AD/LDAP server
        raw: hammer auth-source ldap create --base-dn {{ basedn }}  --attr-firstname "givenName" --attr-lastname "sn" --attr-login "SamAccountName" --attr-mail "mail" --server-type "active_directory" --name AD --host {{ domaincontrollerip }} --onthefly-register --usergroup-sync --account "{{ teamnumber }}\\administrator" --account-password "Netsys1!"

      - name: Fix Hammer role filter permissions for the Default role
        raw: for i in `hammer --output csv filter available-permissions | awk -F, '{ print $1 }'`; do hammer filter create --role "Default role" --permission-ids $i; done

      #- name: ** MANUALLY CHECK THE CREATE USERACCOUNT AT LOGIN BOX **


