- hosts: foreman
  remote_user: root
  strategy: debug

  tasks:
      - name: Add Puppetlabs Repo
        raw: yum -y install https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm

      - name: Install EPEL
        raw: yum -y install http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

      - name: Add Foreman Repo
        raw: yum -y install https://yum.theforeman.org/releases/1.13/el7/x86_64/foreman-release.rpm

      - name: Change Hostname
        raw: hostname foreman.{{ domainname }}

      - name: Download Foreman Installer
        raw: yum -y install foreman-installer

      - name: Install Foreman
        raw: foreman-installer

      - name: Integrate Foreman with team AD/LDAP server
        raw: hammer auth-source ldap create --base-dn {{ basedn }}  --attr-firstname "givenName" --attr-lastname "sn" --attr-login "SamAccountName" --attr-mail "mail" --server-type "active_directory" --name AD --host {{ domaincontrollerip }} --onthefly-register --usergroup-sync --account "{{ teamname }}\\administrator" --account-password "Netsys1!"

      - name: Fix Hammer role filter permissions for the Default role
        raw: for i in `hammer --output csv filter available-permissions | awk -F, '{ print $1 }'`; do hammer filter create --role "Default role" --permission-ids $i; done

      - name: Update admin password to Netsys1!
        raw: hammer user update --login admin --password 'Netsys1!'

      - name: "Manually check the useraccount creation at login box for LDAP auth"
        debug:
          msg: "** MANUALLY CHECK THE CREATE USERACCOUNT AT LOGIN BOX IN THE LDAP SETTINGS **"


