- hosts: salt-masters # Specify from inventory file.
  remote_user: root

  vars:
      master_ip: 192.168.0.2{{ team_number }}

  tasks:
      # If getting an error: "The following signatures couldn't be verified because the public key is not available: NO_PUBKEY <KEY VALUE>" then run:
      # apt-key adv --keyserver keyserver.ubuntu.com --recv-keys <key value>
      #- name: Install software-properties-common for add-apt-repository
      #  raw: apt-get install software-properties-common -y --allow-unauthenticated

      - name: Add the Salt source to the APT source list
        #raw: echo deb http://ppa.launchpad.net/saltstack/salt/ubuntu `lsb_release -sc` main > /etc/apt/sources.list.d/saltstack.list
        raw: echo deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main > /etc/apt/sources.list.d/saltstack.list

      - name: Add Salt Repo Key
        raw: wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -

      - name: Update Apt Cache
        raw: apt-get update

      - name: Install python-apt and xz-utils
        raw: apt-get install python-apt xz-utils -y --allow-unauthenticated      

      - name: Install SaltStack and SaltPad Dependencies
        apt: name={{item}} state=present allow_unauthenticated=yes force=yes
        with_items:
         - salt-master
         - salt-minion
         - salt-api
         - nginx
         - nodejs-legacy
         - npm
         - python-cherrypy

      - name: Deploy Salt-API Config File
        copy: src=../roles/SaltMaster/files/salt-api.conf dest=/etc/salt/master.d/salt-api.conf

      - name: Install python-cherrypy3
        apt: name=python-cherrypy3 state=present allow_unauthenticated=yes force=yes

      - name: bower install
        command: npm -g install bower

      - name: SaltPad git clone
        git: repo=git://github.com/Lothiraldan/saltpad.git dest=/opt/saltpad accept_hostkey=yes

      - name: npm install SaltPad
        npm: path=/opt/saltpad

      - name: bower install saltpad
        bower: path=/opt/saltpad

      - name: Deploy Salt-API Config File
        copy: src=../roles/SaltMaster/files/saltpad-settings.json dest=/opt/saltpad/settings.json
      
      - name: Deploy SaltPad nginx Configuration
        copy: src=../roles/SaltMaster/files/saltpad-nginx.conf dest=/etc/nginx/sites-available/saltpad.conf

      - name: symlink SaltPad nginx Configuration
        file: src=/etc/nginx/sites-available/saltpad.conf dest=/etc/nginx/sites-enabled/default state=link

      - name: Deploy SaltPad front end files
        copy: src=../roles/SaltMaster/files/dist/ dest=/opt/saltpad/

      - name: Copy SaltPad web interface config file
        template: src=../roles/SaltMaster/files/static-settings.j2 dest=/opt/saltpad/static/settings.json
      
      - name: Create pki directory
        file: path=/etc/salt/pki/master/minions state=directory
      
      - name: Restart salt-api
        service: name=salt-api state=restarted

      - name: Restart salt-master
        service: name=salt-master state=restarted

      - name: Restart nginx
        service: name=nginx state=restarted

      # ---- Configure the Salt Web Interface ----
      # Accessible at: http://<SALTMASTER>:8000/saltpad/
      #- name: Saltpad Install
      #  apt: name={{ item }} state=present
      #  with_items:
      #    - nodejs-legacy
      #    - 
