---
- hosts: docker_web_hosts

  tasks:
      - name: Installing Latest Docker Stack.
        shell: curl -fsSL https://get.docker.com/ | sh
        become: yes
        become_user: root
        tags: install_docker

      - name: Copy Docker container to remote host.
        copy: src=../Dockerfile dst=/tmp/Dockerfile
        become: yes
        become_user: root
        tags: copy_dockerbuild

      - name: Dockerbuild
        raw: cd /tmp/; docker build . -t ccdc\www
        become: yes
        become_user: root
        tags: build_dockerwebapp

      - name: Remove dockerbuild file
        raw: rm /tmp/Dockerfile
        become: yes
        become_user: root
        tags: remove_dockerbuild 


- hosts: shipyard_host
  tasks:
      - name: Install Shipyard (Orchestration)
        shell: curl -sSL https://shipyard-project.com/deploy | IMAGE=shipyard/shipyard:test bash -s
        become: yes
        become_user: root
        ignore_errors: yes
        tags: install_shipyard

- hosts: shipyard_nodes
  vars:
    shipyard_server: ec2-52-200-156-245.compute-1.amazonaws.com

  tasks:
      - name: Install Shipyard (Node)
        command: curl -sSL https://shipyard-project.com/deploy | ACTION=node DISCOVERY=etcd://{{ shipyard_server }}:4001 bash -s 
        become: yes
        become_user: root
        tags: shipyard_nodes


# Import Docker image.
#- hosts: container_hosts
#  tasks:
#	  - name: Importing Docker Image
#		command: docker import /tmp/docker-www-prod.tar.gz	
##		become: yes
#		become_user: root
#
