---
- hosts: gentooprod

  tasks:
      - name: Sync Portge.
        shell: sudo emerge --sync
        become: yes
        become_user: root
        tags: init_gentoo 

      - name: Update Portage.
        shell: sudo emerge portage
        become: yes
        become_user: root
        tags: update_ports

      - name: Install Vim.
        shell: sudo emerge vim
        become: yes
        become_user: root
        tags: install_vim

      - name: Install Nginx.
        shell: sudo emerge nginx 
        become: yes
        become_user: root
        tags: install_nginx

      - name: Install Syslog.
        shell: sudo emerge app-admin/syslog-ng 
        become: yes
        become_user: root
        tags: install_syslog

      - name: Install Ansible.
        shell: sudo emerge ansible
        become: yes
        become_user: root
        tags: install_ansible

      - name: Starting syslog.
        shell: sudo systemctl start syslog-ng.service; sudo systemctl enable syslog-ng.service;
        become: yes
        become_user: root
        tags: start_syslog 

      - name: Add users.
        script: ../Configs/newusers
        become: yes
        become_user: root
        tags: add_users

      - name: Modifying user permissions.
        shell: "for user in awsadmin intern2 mysqladmin cloudadmin; do usermod -aG wheel $user; done"
        become: yes
        become_user: root
        tags: mod_permissions

      - name: sudoers modification
        shell: "sudo sed /etc/sudoers -i -e 's/# %wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) NOPASSWD: ALL/'"
        become: yes
        become_user: root
        tags: give_wheel_power
        
      - name: Clear bash history.
        shell: echo "" > ~/.bash_history;
        become: yes
        become_user: root
        tags: clear_bash
