---
- hosts: load_balancer

  tasks:

      - name: Update Portge
        shell: emerge -a sync
        become: yes
        become_user: root
        tags: init_gentoo 

      - name: Install Nginx
        package: nginx state:latest
        become: yes
        become_user: root
        tags: install_nginx

      - name: Copy Config
        src: Configs/loadbalancer.conf
        dest: /etc/nginx/nginx.conf
        owner: nginx
