---
- hosts: Ubuntu_Hosts

  tasks:
      - name: Permit root login via SSH.
        shell: sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        become: yes
        become_user: root
        tags: root_login_allowed.
