---
- hosts: all
  become: yes
  become_user: root


  tasks:
      - name: Permit root login via SSH.
        shell: sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        tags: root_login_allowed.

      - name: VSFTP Install
        apt: name=vsftpd update_cache=yes
        tags: vsftp_install

      - name: MySQL Server Install
        apt: name=mariadb update_cache=yes
        tags: mysql_server

      - name: Add Webmin Repos-1
        shell: "echo deb http://download.webmWebmion.com/download/repository sarge contrib >> /etc/apt/sources.list"
        tags: webmin_key_add-1

      - name: Add Webmin Repos-2
        shell: "echo deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib >> /etc/apt/sources.list"
        tags: webmin_key_add-2

      - name: Add Webmin Key
        shell: "wget http://www.webmin.com/jcameron-key.asc; apt-key add jcameron-key.asc; rm jcameron-key.asc"
        tags: webmin_key_add

      - name: Webmin Install.
        apt: name=webmin update_cache=yes
        tags: root_login_allowed.

      - name: Start Webmin.
        service: name=webmin state=started
        tags: update_cache

      - name: Add users.
        script: ../Configs/newusers
        become: yes
        become_user: root
        tags: add_users

      - name: Clear bash history.
        shell: echo "" > ~/.bash_history;
        become: yes
        become_user: root
        tags: clear_bash
