---
- hosts: ubuntuprod
  become: yes
  become_user: root

  tasks:

        #### SSH
      - name: Permit root login via SSH.
        shell: sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        tags: root_login_allowed.

      - name: SSH Restarting...
        service: name=ssh state=restarted
        tags: ssh_restart

        #### FTP
      - name: VSFTP Install
        apt: name=vsftpd update_cache=yes
        tags: vsftp_install

      - name: Creating default web dir
        file: path=/var/www/ state=directory mode=0777
        tags: make_www

      - name: VSFTPD Vuln config.
        copy: src=../Configs/vsftpd.conf dest=/etc/vsftpd.conf
        tags: vsftp_config

      - name: Restarting VSFTPD
        service: name=vsftpd state=restarted
        tags: vsftp_restart

        #### MySQL
      - name: MySQL-Python 
        apt: name=python-mysqldb update_cache=no
        tags: vsftp_install

      - name: MySQL Server Install
        apt: name=mysql-server update_cache=no
        tags: mysql_server
        
      - name: MySQL Server Config Copy
        copy: src=../Configs/my.cnf dest=/etc/mysql/my.cnf
        tags: mysql_server_config

      - name: MySQL DB create
        mysql_db: name=cc_cards_old state=present
        tags: mysql_db_create

      - name: MySQL SQL-DB Copy
        copy: src=../Configs/MySQL_CC.sql dest=/tmp/cc_db.sql
        tags: mysql_server_config

      - name: MySQL DB Import
        mysql_db: name=all state=import target=/tmp/cc_db.sql
        tags: mysql_db_create

      - name: MySQL Service Restart
        service: name=mysql state=restarted
        tags: mysql_restart_service

      - name: Add Webmin Repos-1
        shell: "echo deb http://download.webmWebmion.com/download/repository sarge contrib >> /etc/apt/sources.list"
        tags: webmin_key_add-1

      - name: Add Webmin Repos-2
        shell: "echo deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib >> /etc/apt/sources.list"
        tags: webmin_key_add-2

      - name: Add Webmin Key
        shell: "wget http://www.webmin.com/jcameron-key.asc; apt-key add jcameron-key.asc; rm jcameron-key.asc"
        tags: webmin_key_add

      - name: Webmin Install.
        apt: name=webmin update_cache=yes
        tags: webmin_install

      - name: Start Webmin.
        service: name=webmin state=started
        tags: start_webmin

      - name: Add users.
        script: ../Configs/newusers
        become: yes
        become_user: root
        tags: add_users

        # Ansible has a user module, but this is easier.
      - name: Granting sudo.
        shell: "for user in awsadmin intern2 mysqladmin cloudadmin; do usermod -aG sudo $user; done"
        become: yes
        become_user: root
        tags: add_users_sudo

      - name: Clear bash history.
        shell: echo "" > ~/.bash_history;
        become: yes
        become_user: root
        tags: clear_bash

      - name: Remove MySQL file.
        shell: rm /tmp/cc_db.sql
        become: yes
        become_user: root
        tags: clear_tmp
